# Generated by Django 4.1.3 on 2022-11-24 17:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('trang_thai', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Car_Customer',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('car_company', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('bien_so', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='choDoXe',
            fields=[
                ('id_parking', models.AutoField(primary_key=True, serialize=False)),
                ('parking_space', models.CharField(max_length=100)),
                ('trang_thai', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id_giave', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('gia_ve', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name_customer', models.CharField(max_length=100)),
                ('phone_customer', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('citizen_identification', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address_customer', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='guixe',
            fields=[
                ('id_guixe', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('tong_tien', models.IntegerField()),
                ('trang_thai', models.BooleanField()),
                ('id_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bill')),
                ('id_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.car_customer')),
                ('id_giave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cost')),
                ('id_parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.chodoxe')),
                ('name_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CheckBienSo',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('bien_so', models.CharField(blank=True, max_length=25)),
                ('trang_thai', models.BooleanField()),
                ('id_checkbienso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car_customer')),
            ],
        ),
        migrations.AddField(
            model_name='car_customer',
            name='id_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.car_customer'),
        ),
    ]
