# Generated by Django 4.1.3 on 2022-11-14 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_staff', models.AutoField(primary_key=True, serialize=False)),
                ('birthday_staff', models.DateField()),
                ('sex_staff', models.CharField(blank=True, max_length=10)),
                ('address_staff', models.CharField(blank=True, max_length=255)),
                ('phone_staff', models.IntegerField()),
                ('name_staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
