# Generated by Django 4.1.3 on 2022-11-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='profileimg',
        ),
        migrations.AddField(
            model_name='admin',
            name='adminimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='admin_images'),
        ),
    ]
